# version : '3.5'
# services:
#     postgres:
#         container_name: postgres
#         build: .
#         restart: always
#         environment:
#             POSTGRES_PASSWORD: neptune
#         ports:
#             - "5432:5432"
#         volumes:
#            - disquaire-postgres-volume:/var/lib/postgresql/data
#         networks:
#            - disquaire-network 
#     pgadmin:
#         container_name: pgadmin
#         restart: always

# volumes:
#     disquaire-postgres-volume:
#         name: disquaire-postgres-volume

# networks:
#     disquaire-network

version: '3.5'

services:
  postgres:
    container_name: postgres_disquaire
    build: .
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - disquaire-postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - disquaire-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_disquaire
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - disquaire-pgadmin-volume:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - disquaire-network
    restart: unless-stopped

networks:
  disquaire-network:
    driver: bridge

volumes:
    disquaire-postgres-volume:
    disquaire-pgadmin-volume: